export const ACTIONS = {
   CART_ADD_ITEM: "CART_ADD_ITEM",
   CART_REMOVE_ITEM: "CART_REMOVE_ITEM",
   CART_INITIAL_ITEMS: "CART_INITIAL_ITEMS",
   CART_RESET: "CART_RESET",
   CART_CLEAR_ITEMS: "CART_CLEAR_ITEMS",
   SAVE_SHIPPING_ADDRESS: "SAVE_SHIPPING_ADDRESS",
   SAVE_PAYMENT_METHOD: "SAVE_PAYMENT_METHOD",
}
